### ISSUE TITLE
Not able to download the QIBA phantoms from globus

### ISSUE THREAD

**Issue by xufeic** [RSNA-QIBA-US-SWS/QIBA-DigitalPhantoms#7]
<img width="1373" alt="issue" src="https://user-images.githubusercontent.com/56868989/196434495-e9615adf-a1b5-4ec9-870b-e062c3ea9d91.png">

Dear Professor Palmeri,

Thank you very much for making so many digital phantoms available to the research community.
I would like to use some of your simulated phantoms for my study. However, the download option is disabled on the globus website (accessed the globus folder from https://research.repository.duke.edu/concern/datasets/qz20st03m?locale=en). Could you please let me know how should I process to download them?
Thank you very much!

Best regards,
Xufei

**Comment by mlp6** [comment]
@xufeic I have put in a help ticket with the Duke folks hosting this to see what the appropriate steps are to access the files via download.  Stay tuned...

**Comment by mlp6** [comment]
@xufeic it turns out that Duke's Research Data Repository does not have the latest version of Globus installed yet, and that latest version is what supports the `Download` option.  Instead, you will need to use the `Transfer or Sync to...` option, which will require download and install of a software client on your machine.  It is a bit of a hassle, but it should work.  Hopefully that direct download functionality will be available sooner than not, but I do not know a specific timeline for that feature.

**Comment by xufeic** [comment]
Dear Professor Palmeri,

I succeeded to download the files using the Transfer or Sync to... option. Thank you very much for your help!!

Best regards,
Xufei
